language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y binutils-dev daemontools libsdl1.2-dev libgtk2.0-dev libxml2-dev libudev-dev libiw-dev

script: 
  - make
